# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f53c010a973b453f52171f65dc76a01846a3c2fc7959a0385781b456c72001d87f5b865fc4c154414b44c9f7143d0f8662d9be443c0ca7d5948bf6829300f9

test:
  secret_key_base: e4c1bdab438cebfeb98df5ce174ff574ce63f04ead625f877ac7f7f58309d23132520539539865fa1b050eab5292300c2fa823140b15116129f1cbd3a1f99684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
